# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ee2546e837f8a6588645de087804f2f9"
application_url = "https://configurations-bite-kiss-lm.trycloudflare.com"
embedded = true
name = "cart-app"
handle = "cart-app-48"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
scopes = "read_app_metafields" , "write_app_metafields"

[auth]
redirect_urls = [
  "https://configurations-bite-kiss-lm.trycloudflare.com/auth/callback",
  "https://configurations-bite-kiss-lm.trycloudflare.com/auth/shopify/callback",
  "https://configurations-bite-kiss-lm.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "zohaibalishah.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
